# Generated by Django 6.0 on 2025-12-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_echeances', models.IntegerField(default=3)),
                ('montant_par_echeance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeanciers', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('REMBOURSÉ', 'Remboursé')], default='EN_ATTENTE', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='VersementEcheance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='paiements.echeancierpaiement')),
            ],
            options={
                'ordering': ['numero_echeance'],
            },
        ),
    ]
