# Generated by Django 6.0 on 2025-12-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee_academique', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('SUSPENDUE', 'Suspendue')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('conditions', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bourses', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
