# Generated by Django 6.0 on 2025-12-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bourse', models.FloatField(default=0)),
                ('boursier', models.CharField(max_length=10)),
                ('numero_inscription', models.CharField(max_length=50, unique=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=12)),
                ('annee_bacc', models.DateField()),
                ('code_redoublement', models.IntegerField(blank=True, null=True)),
                ('faculte', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=15)),
                ('nationalite', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Etudiant/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
